### ISSUE TITLE
running .launch files failed

### ISSUE THREAD

**Issue by liusiping10** [robertoxmed/MC-DAG#1]
Hi, 

thank you for providing the source code, and I am very interested in your work.
but I am a new entry researcher. 

I can run MainGenerator.launch by changing the project name. 

But when I run Ada.launch, DAC.launch, DATE.launch and N_levels.launch will appear: Error: Cannot find or fail to load main class fr.tpt.s3.ls_mxc.alloc.Main 

and running GeneratorTest.launch at the same time appears: 
Error: Cannot find or fail to load main class fr.tpt.s3.ls_mxc.generator.MainGenerator 

Could you solve this problems?

**Comment by robertoxmed** [comment]
Hello,
Thank you for your interest in my research. Sorry for the inconvenience, I did a major refactoring at some point and forgot to update the .launch files. I have updated them but the Ada.launch example is not working at the moment since it uses an old XML model.
I am currently on vacations so I will take a look into that example next week most likely.
